name: d2-net
channels:
- defaults
- pytorch
dependencies:
- python=3.7
- cudatoolkit=10.0
- pip
- pip:
  - torch>=1.5
  - torchvision
  - h5py 
  - imageio
  - imagesize
  - numpy
  - scipy
  - tqdm
  - pyyaml
  - opencv-python
  - opencv-contrib-python
  - matplotlib
  - -e ../multipoint #(manually install w/ pip install ../multipoint) (no -e)

