dataset: 
    filename: ./multipoint_data/test.hdf5
    single_image: False
    random_pairs: False
    return_name : True
    augmentation: 
        photometric: 
            enable: False # Not going to train or test w/ photometric augmentation (hard to say how valid it is on cross-spectral data)
            primitives: all
            params: 
            random_order: True
        homographic: 
            enable: True
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57  # 3.14
                allow_artifacts: true
                translation_overflow: 0.05
            border_reflect: False
            valid_border_margin: 0
            mask_border: True

feature_type: 'd2-net' # 'd2-net' or 'sift'

repeatability: 
    threshold: 4

matching: 
    ratio: 1 # Ratio test ratio
    threshold: 4  # Distance below which two points are considered a match
