dataset: 
    filename: ./multipoint_data/test.hdf5
    single_image: False
    random_pairs: False
    return_name : True
    height: 240
    width: 320
    augmentation: 
        photometric: 
            enable: False # Not going to train or test w/ photometric augmentation (hard to say how valid it is on cross-spectral data)
            primitives: all
            params: 
            random_order: True
        homographic: 
            enable: False
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57  # 3.14
                allow_artifacts: true
                translation_overflow: 0.05
            border_reflect: True
            valid_border_margin: 0
            mask_border: True

feature:
    type: 'd2-orb' # 'd2-net', 'sift', or 'orb', 'd2-orb'
    model: 'models/rosetta-debug-nov-16-3/d2.10.pth' # for d2-net

matching: 
    method: 'ratio' # 'ratio' or 'crosscheck'
    ratio: 0.9 # for ratio test (if used)
    ransac: True # boolean
    
eval: 
    repeat_thresh: 4
    match_thresh: 4  # Distance below which two points are considered a match

saving:
    results_folder: ./results/
